<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\shared\PortalDoCorretor.SharedKernel\PortalDoCorretor.SharedKernel.csproj" />
    <ProjectReference Include="..\..\shared\PortalDoCorretor.Persistence\PortalDoCorretor.Persistence.csproj" />
    <ProjectReference Include="..\..\modules\quotations\PortalDoCorretor.Quotations.Domain\PortalDoCorretor.Quotations.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Npgsql" Version="9.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
